#!/usr/bin/env python
#
# Script to build the files found in this directory.
#------------------------------------------------------------------------------
import os
Import('stntuple_env')
Import('stntuple_helper')
#------------------------------------------------------------------------------
# 2016-10-10: STNTUPLE link: add ROOT 'EG' library after 'Physics' library
#------------------------------------------------------------------------------
def local_build():

    local_env = stntuple_env.Clone();
    babarlibs = local_env['BABARLIBS']
    rootlibs  = local_env['ROOTLIBS' ]
    if ( not ("EG" in rootlibs)):
        rootlibs.insert(rootlibs.index("Physics")+1,"EG");

    debug  = 0
    helper = stntuple_helper(local_env,debug);

    helper.handle_dictionaries();

    list_of_cc_files =  Glob('*.cc', strings=True);
    skip_list        = []
    libs             = ['Stntuple_base', 
                        'Stntuple_geom',
                        'mu2e_CalPatRec',
                        'mu2e_CaloCluster',
                        'mu2e_TrkReco',
                        
                        'mu2e_CalorimeterGeom',
                        'mu2e_GeometryService',
                        'mu2e_SeedService_SeedService_service',
                        'mu2e_GlobalConstantsService',
                        'mu2e_TrackerConditions',
                        'mu2e_ConditionsService',
                        'mu2e_GlobalConstantsService_GlobalConstantsService_service',
                        'mu2e_Mu2eUtilities',
                        'mu2e_GeneralUtilities',
                        
                        'mu2e_MCDataProducts',
                        'mu2e_RecoDataProducts',
                        'mu2e_DataProducts',
                        'mu2e_CaloMC',
                        'mu2e_CommonMC',
                                                
                        babarlibs,
                        
                        'art_Framework_Core',
                        'art_Framework_Principal',
                        'art_Framework_Services_Registry',
                        'art_root_io_tfile_support',
                        'art_root_io_TFileService_service',
                        'art_Persistency_Provenance',
                        'art_Persistency_Common',
                        'art_Utilities',
                        
                            rootlibs, 

                        'fhiclcpp',
                        'MF_MessageLogger.so',
                        'hep_concurrency',
                        'canvas',
                        'cetlib',
                        'cetlib_except',
                        'KinKal_Trajectory',
                        'KinKal_General',
                        'xerces-c',
                        'tracelib'        ,
                        'boost_filesystem',
                        'boost_system'
    ];

    helper.build_libs(list_of_cc_files, skip_list,libs);
#------------------------------------------------------------------------------
local_build();

# print "tmpdir:"+env['STNTUPLE_TMP_LIB_DIR']
